# Generated by Django 5.1.6 on 2025-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=128)),
                ('course_teacher', models.CharField(max_length=128)),
            ],
        ),
    ]
